Vagrant.configure("2") do |config|

  box = "generic/ubuntu2204"
  server_cpu = 2
  server_memory = 2048

  VAGRANT_COMMAND = ARGV[0]
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'ben'
  end

  config.vm.define "test-node0" do |node|
    node.vm.box = box
    node.vm.hostname = "test-node0"
    node.vm.network :private_network, ip: "192.168.121.10"
    node.vm.synced_folder './', '/vagrant', type: 'nfs', nfs_udp: false, nfs_version: 4
    node.vm.provider "libvirt" do |v|
      v.memory = server_memory
      v.cpus = server_cpu
    end
    node.vm.provision "shell", path: "provision.sh"
  end  

  config.vm.define "test-node1" do |node|
    node.vm.box = box
    node.vm.hostname = "test-node1"
    node.vm.network :private_network, ip: "192.168.121.11"
    node.vm.synced_folder './', '/vagrant', type: 'nfs', nfs_udp: false, nfs_version: 4
    node.vm.provider "libvirt" do |v|
      v.memory = server_memory
      v.cpus = server_cpu
    end
    node.vm.provision "shell", path: "provision.sh"
  end
  
  config.vm.define "test-node2" do |node|
    node.vm.box = box
    node.vm.hostname = "test-node2"
    node.vm.network :private_network, ip: "192.168.121.12"
    node.vm.synced_folder './', '/vagrant', type: 'nfs', nfs_udp: false, nfs_version: 4
    node.vm.provider "libvirt" do |v|
      v.memory = server_memory
      v.cpus = server_cpu
    end
    node.vm.provision "shell", path: "provision.sh"
  end
  
  config.vm.define "test-node3" do |node|
    node.vm.box = box
    node.vm.hostname = "test-node3"
    node.vm.network :private_network, ip: "192.168.121.13"
    node.vm.synced_folder './', '/vagrant', type: 'nfs', nfs_udp: false, nfs_version: 4
    node.vm.provider "libvirt" do |v|
      v.memory = server_memory
      v.cpus = server_cpu
    end
    node.vm.provision "shell", path: "provision.sh"
  end
end
